---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sub-service
  namespace: dev
  annotations:
    flux.weave.works/tag.podinfod: semver:>3.0.0
    flux.weave.works/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sub-service
  template:
    metadata:
      labels:
        app: sub-service
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: sub-service
        image: quay.io/brice/metrics-demo:v4-subscription-service
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"

